export const ELEMENTS = {
    iconLogin : '.shop-menu > .nav > :nth-child(4) > a',
    emailInput : '[data-qa="signup-name"]',
    passwordInput : '[data-qa="signup-email"]',
    insertNameInput : '[data-qa="signup-name"]',
    insertEmail : '[data-qa="signup-email"]',
    btnSignup : '[data-qa="signup-button"]',
    redirectPage : ':nth-child(1) > b',
    passwordCreate: '[data-qa="password"]',
    birthDay: '[data-qa="days"]',
    birthMonth: '[data-qa="months"]',
    birthYear: '[data-qa="years"]',
    insertFirstName: '[data-qa="first_name"]',
    insertLastName: '[data-qa="last_name"]',
    companyID:'[data-qa="company"]',
    addressID: '[data-qa="address"]',
    chooseCountry: '[data-qa="country"]',
    insertState: '[data-qa="state"]',
    insertCity: '[data-qa="city"]',
    insertZipCode: '[data-qa="zipcode"]',
    insertPhoneNumber: '[data-qa="mobile_number"]',
    name: 'Luiz',
    email: 'luiz@teste.com',
    gender: '#id_gender1',
    password: '1234554321',
    lastName: 'Costa',
    company: 'Teste Automação',
    address: 'Avenida Santo Amaro, 123 - Santo Amaro',
    state: 'TelAviv',
    city: 'TelAviv',
    code: '05346-000',
    phone: '2 234-099-000'
}