export const ELEMENTS = {
    iconLogin : '.shop-menu > .nav > :nth-child(4) > a',
    emailInput : '[data-qa="signup-name"]',
    passwordInput : '[data-qa="signup-email"]',
    insertNameInput : '[data-qa="signup-name"]',
    insertEmail : '[data-qa="signup-email"]',
    btnSignup : '[data-qa="signup-button"]',
    redirectPage : ':nth-child(1) > b',
    passwordCreate: '[data-qa="password"]',
    birthDay: '[data-qa="days"]',
    birthMonth: '[data-qa="months"]',
    birthYear: '[data-qa="years"]',
    insertFirstName: '[data-qa="first_name"]',
    insertLastName: '[data-qa="last_name"]',
    companyID:'[data-qa="company"]',
    addressID: '[data-qa="address"]',
    chooseCountry: '[data-qa="country"]',
    insertState: '[data-qa="state"]',
    insertCity: '[data-qa="city"]',
    insertZipCode: '[data-qa="zipcode"]',
    insertPhoneNumber: '[data-qa="mobile_number"]',
    gender: '#id_gender1',

    productImage: '[src="/get_product_picture/1"]',
    productQuantity: '#quantity',
    buttonAdd: ".btn.btn-default.cart",
    nameField: '[placeholder="Your Name"]',
    emailField: '#email',
    reviewField: '[placeholder="Add Review Here!"]',

}